/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.SystemAdminWorkArea;

import business.Business;
import business.FlagClass;
import business.Restaurant.Restaurant;
import business.Restaurant.RestaurantDirectory;
import business.event.Event;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author aravindpolepeddi
 */
public class manageEventPanel extends javax.swing.JPanel {

    Business business;
    JPanel workAreaPanel;
    UserAccount account;
    String managerame;
    Event event;
    FlagClass flag;
    Boolean update=false;
    /**
     * Creates new form manageEventPanel
     */
    public manageEventPanel() {
        initComponents();
    }
    
        public manageEventPanel(Business business, UserAccount account, JPanel workAreaPanel) {
        initComponents();
        this.business = business;
        this.workAreaPanel = workAreaPanel;
        this.account = account;
        this.event=new Event();

        flag = new FlagClass();
        

        /*
        JTableHeader tableHeader = tblRestaurantManagers.getTableHeader();
        tableHeader.setFont(new Font("Segoe UI", Font.BOLD, 12));
        ((DefaultTableCellRenderer) tableHeader.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        populateRestaurantRole();
        pnlUpdate.setVisible(false);
        */
        
    }
        
        private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) jEventTable.getModel();
        
        model.setRowCount(0);
        //if(resdir.getRestaurantList()==null){}

        for (Event eve : business.getEventDirectory().getEventList()){
            Object[] row = new Object[5];
            row[0] = eve.getEventName();
            row[1] = eve.getEventType();
            row[2] = eve.getCapacity();
            row[3] = eve.getStartDate();
            row[4] = eve.getEndDate();
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEventTable = new javax.swing.JTable();
        AddEventjButton = new javax.swing.JButton();
        deleteEventjButton = new javax.swing.JButton();
        modifyEventjButton = new javax.swing.JButton();
        eventNamejTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        eventTypejTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        SeatCapacityjTextField = new javax.swing.JTextField();
        jStartDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jEndDateChooser = new com.toedter.calendar.JDateChooser();
        BackjButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(240, 255, 255));

        jEventTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Event Name", "Event Type", "Seating Capacity", "Start Time", "End Time"
            }
        ));
        jScrollPane1.setViewportView(jEventTable);

        AddEventjButton.setBackground(new java.awt.Color(0, 102, 102));
        AddEventjButton.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        AddEventjButton.setForeground(new java.awt.Color(255, 255, 255));
        AddEventjButton.setText("ADD EVENT ");
        AddEventjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEventjButtonActionPerformed(evt);
            }
        });

        deleteEventjButton.setBackground(new java.awt.Color(153, 0, 0));
        deleteEventjButton.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        deleteEventjButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteEventjButton.setText("DELETE EVENT ");
        deleteEventjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEventjButtonActionPerformed(evt);
            }
        });

        modifyEventjButton.setBackground(new java.awt.Color(0, 102, 102));
        modifyEventjButton.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        modifyEventjButton.setForeground(new java.awt.Color(255, 255, 255));
        modifyEventjButton.setText("MODIFY EVENT ");
        modifyEventjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyEventjButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        jLabel1.setText("Event Name");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        jLabel2.setText("Event Type");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        jLabel3.setText("Seating Capacity");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        jLabel4.setText("Event Start Date");

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        jLabel5.setText("Event End Date");

        BackjButton.setBackground(new java.awt.Color(255, 255, 255));
        BackjButton.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        BackjButton.setText("BACK");
        BackjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackjButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Manage Event");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(deleteEventjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(modifyEventjButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(129, 129, 129)
                                .addComponent(BackjButton)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eventNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eventTypejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(155, 155, 155)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jStartDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jEndDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(SeatCapacityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AddEventjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(23, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackjButton)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteEventjButton)
                    .addComponent(modifyEventjButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(eventNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jStartDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(eventTypejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jEndDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddEventjButton)
                    .addComponent(jLabel3)
                    .addComponent(SeatCapacityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddEventjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEventjButtonActionPerformed
        // TODO add your handling code here:
        Date startDate   = jStartDateChooser.getDate();
        Date endDate     = jEndDateChooser.getDate();
        StringBuilder Error = new StringBuilder();
        //if(business.getEventDirectory()==null)
        if(eventNamejTextField.getText().isEmpty() || !business.getEventDirectory().checkIfEventnameIsUnique(eventNamejTextField.getText())){ Error.append("Enter Valid Name \n");}
        else{event.setEventName(eventNamejTextField.getText());
        eventNamejTextField.setText("");}
        if(eventTypejTextField.getText().isEmpty()){ Error.append("Enter Valid Event Type \n");}
        else{event.setEventType(eventTypejTextField.getText());
        eventTypejTextField.setText("");}
        if(SeatCapacityjTextField.getText().isEmpty()){ Error.append("Enter Capacity \n");}
        else{event.setCapacity(Integer.parseInt(SeatCapacityjTextField.getText()));
        SeatCapacityjTextField.setText("");}
        if(startDate.toString().isEmpty()){ Error.append("Enter Valid Start Date \n");}
        else{event.setStartDate(startDate);
        jStartDateChooser.setDate(null);
        }
        if(endDate.toString().isEmpty() || endDate.before(startDate)){ Error.append("Enter Valid End Date \n");}
        else{event.setEndDate(endDate);
        jEndDateChooser.setDate(null);
        }
        if(update==true)
            update=false;
        business.getEventDirectory().createEvent(event);
        populateTable();
    }//GEN-LAST:event_AddEventjButtonActionPerformed

    private void BackjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackjButtonActionPerformed
        // TODO add your handling code here:
        if(update==true) JOptionPane.showMessageDialog(this, "Please Save the updated Event");
        workAreaPanel.remove(this);
        CardLayout layout = (CardLayout) workAreaPanel.getLayout();
        layout.previous(workAreaPanel);
    }//GEN-LAST:event_BackjButtonActionPerformed

    private void deleteEventjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEventjButtonActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = jEventTable.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select an Event");
            return;
        }
        else{
            DefaultTableModel model = (DefaultTableModel) jEventTable.getModel();
            int j=0;
            for(Event e:business.getEventDirectory().getEventList()){
            if(j==selectedRowIndex)
            business.getEventDirectory().getEventList().remove(e);
            break;
            }
            //UserAccount accountToBeRemoved = business.getUserAccountDirectory().fetchUserAccountUsingUserName(selectedUserAccount.getUsername());
            //business.getUserAccountDirectory().removeAccount(accountToBeRemoved);
            JOptionPane.showMessageDialog(null, "Event deleted successfully.");
            populateTable();
        }
    }//GEN-LAST:event_deleteEventjButtonActionPerformed

    private void modifyEventjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyEventjButtonActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = jEventTable.getSelectedRow();        
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a Event");
            return;
        } else {
            DefaultTableModel model = (DefaultTableModel) jEventTable.getModel();
            int j=0;
            for(Event selectedevent:business.getEventDirectory().getEventList()){
            if(j==selectedRowIndex){
            update=true;    
            eventNamejTextField.setText(selectedevent.getEventName());
            eventTypejTextField.setText(selectedevent.getEventType());
            SeatCapacityjTextField.setText(String.valueOf(selectedevent.getCapacity()));
            jStartDateChooser.setDate(selectedevent.getStartDate());
            jEndDateChooser.setDate(selectedevent.getEndDate());
            business.getEventDirectory().getEventList().remove(selectedevent);
            }
            break;
            }
            
            
        }
    }//GEN-LAST:event_modifyEventjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEventjButton;
    private javax.swing.JButton BackjButton;
    private javax.swing.JTextField SeatCapacityjTextField;
    private javax.swing.JButton deleteEventjButton;
    private javax.swing.JTextField eventNamejTextField;
    private javax.swing.JTextField eventTypejTextField;
    private com.toedter.calendar.JDateChooser jEndDateChooser;
    private javax.swing.JTable jEventTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jStartDateChooser;
    private javax.swing.JButton modifyEventjButton;
    // End of variables declaration//GEN-END:variables
}
