/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.SystemAdminWorkArea;

import business.Business;
import business.FlagClass;
import business.event.Event;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aravindpolepeddi
 */
public class manageEventPanel extends javax.swing.JPanel {

    Business business;
    JPanel workAreaPanel;
    UserAccount account;
    String managerame;
    Event event;
    FlagClass flag;
    Boolean update = false;

    /**
     * Creates new form manageEventPanel
     */
    public manageEventPanel() {
        initComponents();
    }

    public manageEventPanel(Business business, UserAccount account, JPanel workAreaPanel) {
        initComponents();
        this.business = business;
        this.workAreaPanel = workAreaPanel;
        this.account = account;
        this.event = new Event();

        flag = new FlagClass();
        populateTable();


        /*
        JTableHeader tableHeader = tblRestaurantManagers.getTableHeader();
        tableHeader.setFont(new Font("Segoe UI", Font.BOLD, 12));
        ((DefaultTableCellRenderer) tableHeader.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        populateRestaurantRole();
        pnlUpdate.setVisible(false);
         */
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) jEventTable.getModel();

        model.setRowCount(0);
        //if(resdir.getRestaurantList()==null){}

        if (business.getEventDirectory() != null && business.getEventDirectory().getEventList() != null && !business.getEventDirectory().getEventList().isEmpty()) {
            for (Event eve : business.getEventDirectory().getEventList()) {
                Object[] row = new Object[5];
                row[0] = eve.getEventName();
                row[1] = eve.getEventType();
                row[2] = eve.getCapacity();
                row[3] = eve.getStartDate();
                row[4] = eve.getEndDate();

                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEventTable = new javax.swing.JTable();
        AddEventjButton = new javax.swing.JButton();
        deleteEventjButton = new javax.swing.JButton();
        modifyEventjButton = new javax.swing.JButton();
        eventNamejTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        eventTypejTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        SeatCapacityjTextField = new javax.swing.JTextField();
        jStartDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jEndDateChooser = new com.toedter.calendar.JDateChooser();
        BackjButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtNetwork = new javax.swing.JTextField();

        jEventTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Event Name", "Event Type", "Seating Capacity", "Start Time", "End Time"
            }
        ));
        jScrollPane1.setViewportView(jEventTable);

        AddEventjButton.setText("Add Event");
        AddEventjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEventjButtonActionPerformed(evt);
            }
        });

        deleteEventjButton.setText("Delete Event");
        deleteEventjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEventjButtonActionPerformed(evt);
            }
        });

        modifyEventjButton.setText("Modify Event");
        modifyEventjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyEventjButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Event Name");

        jLabel2.setText("Event Type");

        jLabel3.setText("Seating Capacity");

        jLabel4.setText("Event Start Date");

        jLabel5.setText("Event End Date");

        BackjButton.setText("Back");
        BackjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackjButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Network");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(deleteEventjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(modifyEventjButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(AddEventjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(BackjButton)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jLabel1)
                                                    .addGap(57, 57, 57))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel2)
                                                    .addGap(63, 63, 63)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel5))
                                                .addGap(24, 24, 24)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(35, 35, 35)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jEndDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jStartDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(eventNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(eventTypejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(SeatCapacityjTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(63, 63, 63)
                                    .addComponent(txtNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(3, 3, 3))))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(12, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteEventjButton)
                            .addComponent(modifyEventjButton))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(BackjButton)
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eventNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(eventTypejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(SeatCapacityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jStartDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jEndDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(AddEventjButton)))
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddEventjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEventjButtonActionPerformed
        Date startDate = jStartDateChooser.getDate();
        Date endDate = jEndDateChooser.getDate();
        StringBuilder Error = new StringBuilder();
        //if(business.getEventDirectory()==null)
        if (eventNamejTextField.getText().isEmpty() || !business.getEventDirectory().checkIfEventnameIsUnique(eventNamejTextField.getText())) {
            Error.append("Enter Valid Name \n");
        } else {
            event.setEventName(eventNamejTextField.getText());
            eventNamejTextField.setText("");
        }
        if (eventTypejTextField.getText().isEmpty()) {
            Error.append("Enter Valid Event Type \n");
        } else {
            event.setEventType(eventTypejTextField.getText());
            eventTypejTextField.setText("");
        }
        if (SeatCapacityjTextField.getText().isEmpty()) {
            Error.append("Enter Capacity \n");
        } else {
            event.setCapacity(Integer.parseInt(SeatCapacityjTextField.getText()));
            SeatCapacityjTextField.setText("");
        }
        if (startDate.toString().isEmpty()) {
            Error.append("Enter Valid Start Date \n");
        } else {
            event.setStartDate(startDate);
            jStartDateChooser.setDate(null);
        }
        if (endDate.toString().isEmpty() || endDate.before(startDate)) {
            Error.append("Enter Valid End Date \n");
        } else {
            event.setEndDate(endDate);
            jEndDateChooser.setDate(null);
        }

        if (txtNetwork.getText().isEmpty()) {
            Error.append("Enter network \n");
        } else {
            event.setNetwork(txtNetwork.getText());
            txtNetwork.setText("");
        }
        if (update == true) {
            update = false;
        }
        business.getEventDirectory().createEvent(event);
        populateTable();
    }//GEN-LAST:event_AddEventjButtonActionPerformed

    private void BackjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackjButtonActionPerformed
        // TODO add your handling code here:
        if (update == true) {
            JOptionPane.showMessageDialog(this, "Please Save the updated Event");
        }
        workAreaPanel.remove(this);
        CardLayout layout = (CardLayout) workAreaPanel.getLayout();
        layout.previous(workAreaPanel);
    }//GEN-LAST:event_BackjButtonActionPerformed

    private void deleteEventjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEventjButtonActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = jEventTable.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select an Event");
            return;
        } else {
            DefaultTableModel model = (DefaultTableModel) jEventTable.getModel();
            int j = 0;
            for (Event e : business.getEventDirectory().getEventList()) {
                if (j == selectedRowIndex) {
                    business.getEventDirectory().getEventList().remove(e);
                }
                break;
            }
            //UserAccount accountToBeRemoved = business.getUserAccountDirectory().fetchUserAccountUsingUserName(selectedUserAccount.getUsername());
            //business.getUserAccountDirectory().removeAccount(accountToBeRemoved);
            JOptionPane.showMessageDialog(null, "Event deleted successfully.");
            populateTable();
        }
    }//GEN-LAST:event_deleteEventjButtonActionPerformed

    private void modifyEventjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyEventjButtonActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = jEventTable.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a Event");
            return;
        } else {
            DefaultTableModel model = (DefaultTableModel) jEventTable.getModel();
            int j = 0;
            for (Event selectedevent : business.getEventDirectory().getEventList()) {
                if (j == selectedRowIndex) {
                    update = true;
                    eventNamejTextField.setText(selectedevent.getEventName());
                    eventTypejTextField.setText(selectedevent.getEventType());
                    SeatCapacityjTextField.setText(String.valueOf(selectedevent.getCapacity()));
                    jStartDateChooser.setDate(selectedevent.getStartDate());
                    jEndDateChooser.setDate(selectedevent.getEndDate());
                    business.getEventDirectory().getEventList().remove(selectedevent);
                }
                break;
            }

        }
    }//GEN-LAST:event_modifyEventjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEventjButton;
    private javax.swing.JButton BackjButton;
    private javax.swing.JTextField SeatCapacityjTextField;
    private javax.swing.JButton deleteEventjButton;
    private javax.swing.JTextField eventNamejTextField;
    private javax.swing.JTextField eventTypejTextField;
    private com.toedter.calendar.JDateChooser jEndDateChooser;
    private javax.swing.JTable jEventTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jStartDateChooser;
    private javax.swing.JButton modifyEventjButton;
    private javax.swing.JTextField txtNetwork;
    // End of variables declaration//GEN-END:variables
}
