/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.SystemAdminWorkArea;

import business.Business;
import business.Customer.Customer;
import business.Customer.CustomerDirectory;
import business.Customer.Ticket;
import business.Customer.TicketDirectory;
import business.Enterprise;
import business.Enterprises.EnterpriseDirectory;
import business.useraccount.UserAccount;
import java.awt.Color;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author deepv
 */
public class StatsPanel extends javax.swing.JPanel {

    TicketDirectory ticketDirectory;
    int foodBevCost;
    Map<String, Enterprise> network;
    EnterpriseDirectory enterpriseDirectory;
    Enterprise enterprise;
    String networkString;
    Business business;
    CustomerDirectory customerDirectory;
    int merchCost;
    int pickDropCost;
    int parkingCost;

    /**
     * Creates new form StatsPanel
     */
    public StatsPanel(Business business, UserAccount account, JPanel workAreaPanel) {
        initComponents();
        this.business = business;

        if (business.getNetworkList() == null) {
            this.network = new HashMap<String, Enterprise>();
        } else {
            this.network = business.getNetworkList();
        }

        cmbNetworks.removeAllItems();
        for (Map.Entry<String, Enterprise> map : network.entrySet()) {
            cmbNetworks.addItem(map.getKey());
        }

        DefaultCategoryDataset dcd = new DefaultCategoryDataset();
        dcd.setValue(foodBevCost, "Food & Beverage revenue", "Food & Beverage");

        JFreeChart jchart = ChartFactory.createBarChart3D("", "ENTERPRISE", "REVENUE", dcd, PlotOrientation.VERTICAL, true, true, false);
        CategoryPlot plot = jchart.getCategoryPlot();
        plot.setRangeGridlinePaint(Color.black);
        ChartFrame chartFrm = new ChartFrame("Student Record", jchart, true);
        chartFrm.setVisible(true);
        chartFrm.setSize(500, 400);
        ChartPanel chartPanel = new ChartPanel(jchart);
        chartFrm.dispose();
        pnlChart.removeAll();
        pnlChart.add(chartPanel);
        pnlChart.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRestaurantName1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        pnlChart = new javax.swing.JPanel();
        cmbNetworks = new javax.swing.JComboBox<>();
        btnNetwork = new javax.swing.JButton();

        setBackground(new java.awt.Color(240, 255, 255));

        lblRestaurantName1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRestaurantName1.setForeground(new java.awt.Color(0, 153, 153));
        lblRestaurantName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRestaurantName1.setText("STATS");

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setText("BACK");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setFocusPainted(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        pnlChart.setBackground(new java.awt.Color(240, 255, 255));
        pnlChart.setLayout(new javax.swing.BoxLayout(pnlChart, javax.swing.BoxLayout.LINE_AXIS));

        cmbNetworks.setBackground(new java.awt.Color(255, 255, 255));
        cmbNetworks.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmbNetworks.setForeground(new java.awt.Color(0, 51, 51));

        btnNetwork.setBackground(new java.awt.Color(0, 153, 153));
        btnNetwork.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNetwork.setForeground(new java.awt.Color(0, 51, 51));
        btnNetwork.setText("SUBMIT NETWORK");
        btnNetwork.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNetworkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(lblRestaurantName1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addGap(127, 127, 127))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(pnlChart, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(cmbNetworks, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnNetwork)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRestaurantName1)
                    .addComponent(jButton7))
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbNetworks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNetwork))
                .addGap(18, 18, 18)
                .addComponent(pnlChart, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNetworkActionPerformed

        this.foodBevCost = 0;

        this.enterprise = business.findEnterpriseByNetwork(cmbNetworks.getSelectedItem().toString());

        if (enterprise.getTicketDirectory() == null) {
            this.ticketDirectory = new TicketDirectory();
        } else {
            this.ticketDirectory = enterprise.getTicketDirectory();
        }

        for (Ticket ticket : ticketDirectory.getTicketList()) {
            foodBevCost = foodBevCost + ticket.getFoodCost() + ticket.getReservationCost();
        }

        this.merchCost = 0;
        if (enterprise.getCustomerDirectory() == null) {
            this.customerDirectory = new CustomerDirectory();
        } else {
            this.customerDirectory = enterprise.getCustomerDirectory();
        }

        for (Customer customer : customerDirectory.getCustomers()) {
            merchCost = merchCost + customer.getMerchCost();
        }

        this.pickDropCost = 0;
        for (Customer customer : customerDirectory.getCustomers()) {
            pickDropCost = pickDropCost + customer.getPickDropCost();
        }
        this.parkingCost = 0;
        for (Customer customer : customerDirectory.getCustomers()) {
            parkingCost = parkingCost + customer.getParkingCost();
        }

        DefaultCategoryDataset dcd = new DefaultCategoryDataset();
        dcd.setValue(foodBevCost, "Food & Beverage revenue", "Food & Beverage");
        dcd.setValue(merchCost, "Merchandise revenue", "Merchandise");
        dcd.setValue(parkingCost + pickDropCost, "Bookings revenue", "Bookings");

        JFreeChart jchart = ChartFactory.createBarChart3D("", "ENTERPRISE", "REVENUE", dcd, PlotOrientation.VERTICAL, true, true, false);
        CategoryPlot plot = jchart.getCategoryPlot();
        plot.setRangeGridlinePaint(Color.black);
        ChartFrame chartFrm = new ChartFrame("Student Record", jchart, true);
        chartFrm.setVisible(true);
        chartFrm.setSize(500, 400);
        ChartPanel chartPanel = new ChartPanel(jchart);
        chartFrm.dispose();
        pnlChart.removeAll();
        pnlChart.add(chartPanel);
        pnlChart.updateUI();
    }//GEN-LAST:event_btnNetworkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNetwork;
    private javax.swing.JComboBox<String> cmbNetworks;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel lblRestaurantName1;
    private javax.swing.JPanel pnlChart;
    // End of variables declaration//GEN-END:variables
}
