/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Organization.HR;

import business.Business;
import business.hrservices.CleaningServicesDirectory;
import business.hrservices.EmergencyServices;
import business.hrservices.EmergencyServicesDirectory;
import business.useraccount.UserAccount;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author deepv
 */
public class EmergencyServicesJPanel extends javax.swing.JPanel {

    EmergencyServicesDirectory emergencyServiceDirectory;
    EmergencyServices emergencyServiceFetch;

    /**
     * Creates new form EmergencyServicesJPanel
     */
    public EmergencyServicesJPanel(JPanel userProcessContainer, UserAccount account, Business business) {
        initComponents();

        if (business.getEmergencyServices() == null) {
            this.emergencyServiceDirectory = new EmergencyServicesDirectory();
        } else {
            this.emergencyServiceDirectory = business.getEmergencyServices();
        }

        emergencyServiceFetch = emergencyServiceDirectory.findEmergencyServiceByManagerName(account.getName());

        if (emergencyServiceFetch != null) {
            lblAmbulanceCount.setText(String.valueOf(emergencyServiceFetch.getNumOfAmbulances()));
            lblFireBrigadeCount.setText(String.valueOf(emergencyServiceFetch.getNumOfFireBrigades()));
            lblFirstAidKitCount.setText(String.valueOf(emergencyServiceFetch.getNumOfFirstAidKits()));
            lblAirAmbulanceCount.setText(String.valueOf(emergencyServiceFetch.getNumOfAirAmbulance()));
        } else {
            lblAmbulanceCount.setText("--");
            lblFireBrigadeCount.setText("--");
            lblFirstAidKitCount.setText("--");
            lblAirAmbulanceCount.setText("--");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        navigationPanel = new javax.swing.JPanel();
        btnEditDetails = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        EmergencyDashboard = new javax.swing.JPanel();
        lblRestaurantName = new javax.swing.JLabel();
        lblAmbulance = new javax.swing.JLabel();
        lblFireBrigades = new javax.swing.JLabel();
        lblFirstAidKits = new javax.swing.JLabel();
        lblAirAmbulance = new javax.swing.JLabel();
        lblAmbulanceCount = new javax.swing.JLabel();
        lblFireBrigadeCount = new javax.swing.JLabel();
        lblFirstAidKitCount = new javax.swing.JLabel();
        lblAirAmbulanceCount = new javax.swing.JLabel();
        AddProvisions = new javax.swing.JPanel();
        lblRestaurantName1 = new javax.swing.JLabel();
        btnBack5 = new javax.swing.JButton();
        lblAmbulance1 = new javax.swing.JLabel();
        lblFireBrigades1 = new javax.swing.JLabel();
        lblFirstAidKits1 = new javax.swing.JLabel();
        lblAirAmbulance1 = new javax.swing.JLabel();
        txtAmbulanceCount = new javax.swing.JTextField();
        txtFireBrigadeCount = new javax.swing.JTextField();
        txtFirstAidCount = new javax.swing.JTextField();
        txtAirAmbulanceCount = new javax.swing.JTextField();
        btnBack4 = new javax.swing.JButton();

        navigationPanel.setBackground(new java.awt.Color(0, 51, 51));

        btnEditDetails.setBackground(new java.awt.Color(206, 217, 217));
        btnEditDetails.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditDetails.setForeground(new java.awt.Color(0, 51, 51));
        btnEditDetails.setText("ADD PROVISIONS");
        btnEditDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditDetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditDetailsMouseExited(evt);
            }
        });
        btnEditDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navigationPanelLayout = new javax.swing.GroupLayout(navigationPanel);
        navigationPanel.setLayout(navigationPanelLayout);
        navigationPanelLayout.setHorizontalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navigationPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        navigationPanelLayout.setVerticalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(btnEditDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(401, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(navigationPanel);

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        EmergencyDashboard.setBackground(new java.awt.Color(240, 255, 255));

        lblRestaurantName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRestaurantName.setForeground(new java.awt.Color(0, 153, 153));
        lblRestaurantName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRestaurantName.setText("EMERGENCY SERVICES");

        lblAmbulance.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAmbulance.setText("AMBULANCES : ");

        lblFireBrigades.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFireBrigades.setText("FIRE BRIGADES : ");

        lblFirstAidKits.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFirstAidKits.setText("FIRST AID KITS : ");

        lblAirAmbulance.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAirAmbulance.setText("AIR AMBULANCE : ");

        lblAmbulanceCount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAmbulanceCount.setText("--");

        lblFireBrigadeCount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFireBrigadeCount.setText("--");

        lblFirstAidKitCount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFirstAidKitCount.setText("--");

        lblAirAmbulanceCount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAirAmbulanceCount.setText("--");

        javax.swing.GroupLayout EmergencyDashboardLayout = new javax.swing.GroupLayout(EmergencyDashboard);
        EmergencyDashboard.setLayout(EmergencyDashboardLayout);
        EmergencyDashboardLayout.setHorizontalGroup(
            EmergencyDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRestaurantName, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
            .addGroup(EmergencyDashboardLayout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addGroup(EmergencyDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAmbulance, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFireBrigades, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFirstAidKits, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAirAmbulance, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EmergencyDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAmbulanceCount)
                    .addComponent(lblFireBrigadeCount)
                    .addComponent(lblFirstAidKitCount)
                    .addComponent(lblAirAmbulanceCount))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EmergencyDashboardLayout.setVerticalGroup(
            EmergencyDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmergencyDashboardLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblRestaurantName)
                .addGap(86, 86, 86)
                .addGroup(EmergencyDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAmbulance)
                    .addComponent(lblAmbulanceCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EmergencyDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFireBrigades)
                    .addComponent(lblFireBrigadeCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EmergencyDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstAidKits)
                    .addComponent(lblFirstAidKitCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EmergencyDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAirAmbulance)
                    .addComponent(lblAirAmbulanceCount))
                .addContainerGap(408, Short.MAX_VALUE))
        );

        jLayeredPane1.add(EmergencyDashboard, "card2");

        AddProvisions.setBackground(new java.awt.Color(240, 255, 255));

        lblRestaurantName1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRestaurantName1.setForeground(new java.awt.Color(0, 153, 153));
        lblRestaurantName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRestaurantName1.setText("Add Provisions");

        btnBack5.setBackground(new java.awt.Color(255, 204, 204));
        btnBack5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack5.setForeground(new java.awt.Color(255, 0, 51));
        btnBack5.setText("BACK");
        btnBack5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBack5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBack5MouseExited(evt);
            }
        });
        btnBack5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack5ActionPerformed(evt);
            }
        });

        lblAmbulance1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAmbulance1.setText("AMBULANCES : ");

        lblFireBrigades1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFireBrigades1.setText("FIRE BRIGADES : ");

        lblFirstAidKits1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFirstAidKits1.setText("FIRST AID KITS : ");

        lblAirAmbulance1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAirAmbulance1.setText("AIR AMBULANCE : ");

        txtFirstAidCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstAidCountActionPerformed(evt);
            }
        });

        btnBack4.setBackground(new java.awt.Color(215, 254, 211));
        btnBack4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack4.setForeground(new java.awt.Color(72, 151, 64));
        btnBack4.setText("ADD");
        btnBack4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBack4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBack4MouseExited(evt);
            }
        });
        btnBack4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddProvisionsLayout = new javax.swing.GroupLayout(AddProvisions);
        AddProvisions.setLayout(AddProvisionsLayout);
        AddProvisionsLayout.setHorizontalGroup(
            AddProvisionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRestaurantName1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddProvisionsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack5)
                .addGap(71, 71, 71))
            .addGroup(AddProvisionsLayout.createSequentialGroup()
                .addGroup(AddProvisionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddProvisionsLayout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addGroup(AddProvisionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAmbulance1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFireBrigades1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFirstAidKits1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAirAmbulance1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(AddProvisionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAmbulanceCount, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFireBrigadeCount, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFirstAidCount, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAirAmbulanceCount, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AddProvisionsLayout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(btnBack4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AddProvisionsLayout.setVerticalGroup(
            AddProvisionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddProvisionsLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(AddProvisionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAirAmbulanceCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AddProvisionsLayout.createSequentialGroup()
                        .addComponent(btnBack5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRestaurantName1)
                        .addGap(139, 139, 139)
                        .addGroup(AddProvisionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAmbulance1)
                            .addComponent(txtAmbulanceCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AddProvisionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFireBrigades1)
                            .addComponent(txtFireBrigadeCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AddProvisionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFirstAidKits1)
                            .addComponent(txtFirstAidCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAirAmbulance1)))
                .addGap(82, 82, 82)
                .addComponent(btnBack4)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        jLayeredPane1.add(AddProvisions, "card3");

        jSplitPane1.setRightComponent(jLayeredPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditDetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditDetailsMouseEntered

    }//GEN-LAST:event_btnEditDetailsMouseEntered

    private void btnEditDetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditDetailsMouseExited

    }//GEN-LAST:event_btnEditDetailsMouseExited

    private void btnEditDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditDetailsActionPerformed
        switchPanels(AddProvisions);
    }//GEN-LAST:event_btnEditDetailsActionPerformed

    private void btnBack5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBack5MouseEntered

    }//GEN-LAST:event_btnBack5MouseEntered

    private void btnBack5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBack5MouseExited

    }//GEN-LAST:event_btnBack5MouseExited

    private void btnBack5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack5ActionPerformed
        switchPanels(EmergencyDashboard);
    }//GEN-LAST:event_btnBack5ActionPerformed

    private void txtFirstAidCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstAidCountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstAidCountActionPerformed

    private void btnBack4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBack4MouseEntered

    }//GEN-LAST:event_btnBack4MouseEntered

    private void btnBack4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBack4MouseExited

    }//GEN-LAST:event_btnBack4MouseExited

    private void btnBack4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack4ActionPerformed
        emergencyServiceFetch.setNumOfAmbulances(Integer.parseInt(txtAmbulanceCount.getText()));
        emergencyServiceFetch.setNumOfFireBrigades(Integer.valueOf(txtFireBrigadeCount.getText()));
        emergencyServiceFetch.setNumOfFirstAidKits(Integer.valueOf(txtFirstAidCount.getText()));
        emergencyServiceFetch.setNumOfAirAmbulance(Integer.parseInt(txtAirAmbulanceCount.getText()));
        
        JOptionPane.showMessageDialog(null, "Provisions added successfully.");
        lblAmbulanceCount.setText(txtAmbulanceCount.getText());
        lblFireBrigadeCount.setText(txtFireBrigadeCount.getText());
        lblFirstAidKitCount.setText(txtFirstAidCount.getText());
        lblAirAmbulanceCount.setText(txtAirAmbulanceCount.getText());
        switchPanels(EmergencyDashboard);
        txtAmbulanceCount.setText("");
        txtFireBrigadeCount.setText("");
        txtFirstAidCount.setText("");
        txtAirAmbulanceCount.setText("");
    }//GEN-LAST:event_btnBack4ActionPerformed

    private void switchPanels(Component component) {
        jLayeredPane1.removeAll();
        jLayeredPane1.add(component);
        jLayeredPane1.revalidate();
        jLayeredPane1.repaint();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddProvisions;
    private javax.swing.JPanel EmergencyDashboard;
    private javax.swing.JButton btnBack4;
    private javax.swing.JButton btnBack5;
    private javax.swing.JButton btnEditDetails;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblAirAmbulance;
    private javax.swing.JLabel lblAirAmbulance1;
    private javax.swing.JLabel lblAirAmbulanceCount;
    private javax.swing.JLabel lblAmbulance;
    private javax.swing.JLabel lblAmbulance1;
    private javax.swing.JLabel lblAmbulanceCount;
    private javax.swing.JLabel lblFireBrigadeCount;
    private javax.swing.JLabel lblFireBrigades;
    private javax.swing.JLabel lblFireBrigades1;
    private javax.swing.JLabel lblFirstAidKitCount;
    private javax.swing.JLabel lblFirstAidKits;
    private javax.swing.JLabel lblFirstAidKits1;
    private javax.swing.JLabel lblRestaurantName;
    private javax.swing.JLabel lblRestaurantName1;
    private javax.swing.JPanel navigationPanel;
    private javax.swing.JTextField txtAirAmbulanceCount;
    private javax.swing.JTextField txtAmbulanceCount;
    private javax.swing.JTextField txtFireBrigadeCount;
    private javax.swing.JTextField txtFirstAidCount;
    // End of variables declaration//GEN-END:variables
}
