/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Enterprises;

import business.Business;
import business.hrservices.CleaningServices;
import business.hrservices.CleaningServicesDirectory;
import business.hrservices.EmergencyServices;
import business.hrservices.EmergencyServicesDirectory;
import business.hrservices.TechnicalServices;
import business.hrservices.TechnicalServicesDirectory;
import business.hrservices.SecurityServices;
import business.hrservices.SecurityServicesDirectory;
import business.premium.Premium;
import business.role.CleaningServicesRole;
import business.role.EmergencyServicesRole;
import business.role.HumanResourceEntAdmin;
import business.role.RestaurantRole;
import business.role.Role;
import business.role.SecurityServicesRole;
import business.role.TechnicalServicesRole;
import business.suites.Suites;
import business.suites.SuitesDirectory;
import business.useraccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author deepv
 */
public class HumanResourcesEntJPanel extends javax.swing.JPanel {

    Business business;
    CleaningServicesDirectory cleaningServices;
    EmergencyServicesDirectory emergencyServices;
    TechnicalServicesDirectory technicalServices;
    SecurityServicesDirectory securityServices;

    /**
     * Creates new form HumanResourcesEntJPanel
     */
    public HumanResourcesEntJPanel(JPanel userProcessContainer, UserAccount account, Business business) {
        initComponents();

        this.business = business;
        if (business.getCleaningServices() == null) {
            this.cleaningServices = new CleaningServicesDirectory();
        } else {
            this.cleaningServices = business.getCleaningServices();
        }

        if (business.getEmergencyServices() == null) {
            this.emergencyServices = new EmergencyServicesDirectory();
        } else {
            this.emergencyServices = business.getEmergencyServices();
        }

        if (business.getTechnicalServices() == null) {
            this.technicalServices = new TechnicalServicesDirectory();
        } else {
            this.technicalServices = business.getTechnicalServices();
        }

        if (business.getSecurityServices() == null) {
            this.securityServices = new SecurityServicesDirectory();
        } else {
            this.securityServices = business.getSecurityServices();
        }

        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        NavigationJPanel = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        workAreaPanel = new javax.swing.JPanel();
        lblRestaurantName1 = new javax.swing.JLabel();
        lblAddUser2 = new javax.swing.JLabel();
        lblManagerName2 = new javax.swing.JLabel();
        txtManagerName = new javax.swing.JTextField();
        lblRestaurantName4 = new javax.swing.JLabel();
        lblUserName2 = new javax.swing.JLabel();
        txtManagerUsername2 = new javax.swing.JTextField();
        lblPassword2 = new javax.swing.JLabel();
        pwdManagerPassword2 = new javax.swing.JPasswordField();
        btnUpdateUser = new javax.swing.JButton();
        btnDelete1 = new javax.swing.JButton();
        btnUpdate1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHumanResourceManagers = new javax.swing.JTable();
        cmbServices = new javax.swing.JComboBox<>();
        lblAddUser3 = new javax.swing.JLabel();
        lblManagerName3 = new javax.swing.JLabel();
        lblRestaurantName5 = new javax.swing.JLabel();
        lblUserName3 = new javax.swing.JLabel();
        lblPassword3 = new javax.swing.JLabel();
        txtManagerName2 = new javax.swing.JTextField();
        cmbServices2 = new javax.swing.JComboBox<>();
        txtManagerUsername1 = new javax.swing.JTextField();
        pwdManagerPassword1 = new javax.swing.JPasswordField();
        btnCreateUser2 = new javax.swing.JButton();

        NavigationJPanel.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout NavigationJPanelLayout = new javax.swing.GroupLayout(NavigationJPanel);
        NavigationJPanel.setLayout(NavigationJPanelLayout);
        NavigationJPanelLayout.setHorizontalGroup(
            NavigationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        NavigationJPanelLayout.setVerticalGroup(
            NavigationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(NavigationJPanel);

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        workAreaPanel.setBackground(new java.awt.Color(240, 255, 255));

        lblRestaurantName1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRestaurantName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRestaurantName1.setText("Human Resources");

        lblAddUser2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAddUser2.setForeground(new java.awt.Color(0, 102, 102));
        lblAddUser2.setText("ADD NEW USER");

        lblManagerName2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblManagerName2.setText("Manager Name :");

        lblRestaurantName4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRestaurantName4.setText("Service Name:");

        lblUserName2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUserName2.setText("Username : ");

        lblPassword2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPassword2.setText("Password : ");

        btnUpdateUser.setBackground(new java.awt.Color(0, 102, 102));
        btnUpdateUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdateUser.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateUser.setText("UPDATE");
        btnUpdateUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateUserMouseExited(evt);
            }
        });
        btnUpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUserActionPerformed(evt);
            }
        });

        btnDelete1.setBackground(new java.awt.Color(153, 0, 0));
        btnDelete1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete1.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete1.setText("DELETE USER");
        btnDelete1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDelete1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDelete1MouseExited(evt);
            }
        });
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });

        btnUpdate1.setBackground(new java.awt.Color(0, 102, 102));
        btnUpdate1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate1.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate1.setText("UPDATE USER");
        btnUpdate1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdate1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdate1MouseExited(evt);
            }
        });
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });

        tblHumanResourceManagers.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblHumanResourceManagers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "USER NAME", "PASSWORD", "MANAGER NAME", "SERVICE TYPE"
            }
        ));
        tblHumanResourceManagers.setSelectionBackground(new java.awt.Color(153, 209, 232));
        tblHumanResourceManagers.setSelectionForeground(new java.awt.Color(0, 51, 51));
        jScrollPane3.setViewportView(tblHumanResourceManagers);

        cmbServices.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT SERVICE", "CLEANING", "EMERGENCY", "TECHNICAL", "SECURITY" }));

        lblAddUser3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAddUser3.setForeground(new java.awt.Color(0, 102, 102));
        lblAddUser3.setText("UPDATE  USER");

        lblManagerName3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblManagerName3.setText("Manager Name :");

        lblRestaurantName5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRestaurantName5.setText("Service Name:");

        lblUserName3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUserName3.setText("Username : ");

        lblPassword3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPassword3.setText("Password : ");

        cmbServices2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT SERVICE", "CLEANING", "EMERGENCY", "TECHNICAL", "SECURITY" }));

        btnCreateUser2.setBackground(new java.awt.Color(0, 102, 102));
        btnCreateUser2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCreateUser2.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateUser2.setText("CREATE");
        btnCreateUser2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCreateUser2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCreateUser2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCreateUser2MouseExited(evt);
            }
        });
        btnCreateUser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUser2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout workAreaPanelLayout = new javax.swing.GroupLayout(workAreaPanel);
        workAreaPanel.setLayout(workAreaPanelLayout);
        workAreaPanelLayout.setHorizontalGroup(
            workAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, workAreaPanelLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(lblAddUser3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAddUser2)
                .addGap(291, 291, 291))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, workAreaPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(workAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblManagerName3)
                    .addComponent(lblRestaurantName5)
                    .addComponent(lblUserName3)
                    .addComponent(lblPassword3))
                .addGap(38, 38, 38)
                .addGroup(workAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pwdManagerPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtManagerUsername2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbServices2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtManagerName2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addGroup(workAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, workAreaPanelLayout.createSequentialGroup()
                        .addComponent(lblManagerName2)
                        .addGap(18, 18, 18)
                        .addComponent(txtManagerName, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(workAreaPanelLayout.createSequentialGroup()
                        .addGroup(workAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRestaurantName4)
                            .addComponent(lblPassword2)
                            .addComponent(lblUserName2))
                        .addGap(32, 32, 32)
                        .addGroup(workAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtManagerUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbServices, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pwdManagerPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCreateUser2))))
                .addGap(228, 228, 228))
            .addGroup(workAreaPanelLayout.createSequentialGroup()
                .addGroup(workAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRestaurantName1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(workAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(workAreaPanelLayout.createSequentialGroup()
                            .addGap(126, 126, 126)
                            .addComponent(btnUpdateUser))
                        .addGroup(workAreaPanelLayout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addGroup(workAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(workAreaPanelLayout.createSequentialGroup()
                                    .addComponent(btnDelete1)
                                    .addGap(424, 424, 424)
                                    .addComponent(btnUpdate1))
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        workAreaPanelLayout.setVerticalGroup(
            workAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAreaPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblRestaurantName1)
                .addGap(68, 68, 68)
                .addGroup(workAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate1)
                    .addComponent(btnDelete1))
                .addGap(18, 18, 18)
                .addGroup(workAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(workAreaPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(workAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAddUser2)
                            .addComponent(lblAddUser3))
                        .addGap(18, 18, 18)
                        .addGroup(workAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblManagerName2)
                            .addComponent(txtManagerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblManagerName3)
                            .addComponent(txtManagerName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(workAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRestaurantName4)
                            .addComponent(cmbServices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRestaurantName5)
                            .addComponent(cmbServices2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(workAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUserName2)
                            .addComponent(txtManagerUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, workAreaPanelLayout.createSequentialGroup()
                        .addGroup(workAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtManagerUsername2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUserName3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(workAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassword2)
                    .addGroup(workAreaPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(workAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pwdManagerPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPassword3)))
                    .addComponent(pwdManagerPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(workAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateUser)
                    .addComponent(btnCreateUser2))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        jLayeredPane1.add(workAreaPanel, "card2");

        jSplitPane1.setRightComponent(jLayeredPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 912, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateUserMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateUserMouseEntered

    private void btnUpdateUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateUserMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateUserMouseExited

    private void btnUpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUserActionPerformed
        boolean formDatafilled = true;
        if (!validateStringInput(txtManagerName2.getText())) {
            formDatafilled = false;
            JOptionPane.showMessageDialog(this, "Please enter Manager name");
        }
        if (!validateStringInput(txtManagerUsername2.getText())) {
            formDatafilled = false;
             JOptionPane.showMessageDialog(this, "Please enter username ");
        }
        if (!validateStringInput(pwdManagerPassword2.getText())) {
            formDatafilled = false;
            JOptionPane.showMessageDialog(this, "Please enter password");
        }

        if(formDatafilled){
            //save data
               String userName = txtManagerUsername2.getText();
        String password = pwdManagerPassword2.getText();
        String serviceType = cmbServices.getSelectedItem().toString();
        String managerame = txtManagerName2.getText();

        if (!business.getUserAccountDirectory().checkIfUsernameIsUnique(userName)) {
            JOptionPane.showMessageDialog(null, "UserName already taken!");
            txtManagerUsername2.setText("");
            pwdManagerPassword2.setText("");
        } else {

            if (serviceType.equals("CLEANING")) {
                CleaningServices cleaningService = cleaningServices.addCleaningService();
                cleaningService.setManagerName(managerame);
                cleaningService.setUserName(userName);
                cleaningService.setManagerType("CLEANING");
                business.setCleaningServices(cleaningServices);
                CleaningServicesRole role = new CleaningServicesRole();
                business.getUserAccountDirectory().createUserAccount(userName, managerame, password, role);
            } else if (serviceType.equals("EMERGENCY")) {
                EmergencyServices emergencyService = emergencyServices.addEmergencyService();
                emergencyService.setManagerName(managerame);
                emergencyService.setUserName(userName);
                emergencyService.setManagerType("EMERGENCY");
                business.setEmergencyServices(emergencyServices);
                EmergencyServicesRole role = new EmergencyServicesRole();
                business.getUserAccountDirectory().createUserAccount(userName, managerame, password, role);
            } else if (serviceType.equals("TECHNICAL")) {
                TechnicalServices technicalService = technicalServices.addGroundService();
                technicalService.setManagerName(managerame);
                technicalService.setUserName(userName);
                technicalService.setManagerType("TECHNICAL");
                business.setTechnicalServices(technicalServices);
                TechnicalServicesRole role = new TechnicalServicesRole();
                business.getUserAccountDirectory().createUserAccount(userName, managerame, password, role);
            } else if (serviceType.equals("SECURITY")) {
                SecurityServices securityService = securityServices.addSecurityService();
                securityService.setManagerName(managerame);
                securityService.setUserName(userName);
                securityService.setManagerType("SECURITY");
                business.setSecurityServices(securityServices);
                SecurityServicesRole role = new SecurityServicesRole();
                business.getUserAccountDirectory().createUserAccount(userName, managerame, password, role);
            }

            txtManagerName2.setText("");
            cmbServices2.setSelectedItem("SELECT SERVICE");
            txtManagerUsername2.setText("");
            pwdManagerPassword2.setText("");

            populateTable();
        }
        }
    }//GEN-LAST:event_btnUpdateUserActionPerformed

    private void btnDelete1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelete1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelete1MouseEntered

    private void btnDelete1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelete1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelete1MouseExited

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed
        int selectedRowIndex = tblHumanResourceManagers.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a User");
            return;
        } else {
            DefaultTableModel model = (DefaultTableModel) tblHumanResourceManagers.getModel();
            UserAccount selectedUserAccount = (UserAccount) model.getValueAt(selectedRowIndex, 0);
            UserAccount accountToBeRemoved = business.getUserAccountDirectory().fetchUserAccountUsingUserName(selectedUserAccount.getUsername());
            business.getUserAccountDirectory().removeAccount(accountToBeRemoved);
            JOptionPane.showMessageDialog(null, "User Account deleted successfully.");
            populateTable();

            CleaningServices removedCleaningService = cleaningServices.findCleaningServiceByManagerName(selectedUserAccount.getName());
            if (removedCleaningService != null) {
                cleaningServices.removeCleaningService(removedCleaningService);
            }

            EmergencyServices removedEmergencyServices = emergencyServices.findEmergencyServiceByManagerName(selectedUserAccount.getName());
            if (removedEmergencyServices != null) {
                emergencyServices.removeEmergencyService(removedEmergencyServices);
            }

            TechnicalServices removedGroundServices = technicalServices.findTechServiceByManagerName(selectedUserAccount.getName());
            if (removedGroundServices != null) {
                technicalServices.removeGroundService(removedGroundServices);
            }

            SecurityServices removedSecurityServices = securityServices.findSecurityServiceByManagerName(selectedUserAccount.getName());
            if (removedSecurityServices != null) {
                securityServices.removeSecurityService(removedSecurityServices);
            }
        }
    }//GEN-LAST:event_btnDelete1ActionPerformed

    private void btnUpdate1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdate1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate1MouseEntered

    private void btnUpdate1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdate1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate1MouseExited

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed
        int selectedRowIndex = tblHumanResourceManagers.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a User");
            return;
        } else {
            DefaultTableModel model = (DefaultTableModel) tblHumanResourceManagers.getModel();
            UserAccount selectedUserAccount = (UserAccount) model.getValueAt(selectedRowIndex, 0);
        }
    }//GEN-LAST:event_btnUpdate1ActionPerformed

    private void btnCreateUser2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateUser2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateUser2MouseEntered

    private void btnCreateUser2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateUser2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateUser2MouseExited

    private void btnCreateUser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUser2ActionPerformed
        // TODO add your handling code here:
        boolean formDatafilled = true;
        if (!validateStringInput(txtManagerName.getText())) {
            formDatafilled = false;
            JOptionPane.showMessageDialog(this, "Please enter Manager name");
        }
        if (!validateStringInput(txtManagerUsername1.getText())) {
            formDatafilled = false;
             JOptionPane.showMessageDialog(this, "Please enter username ");
        }
        if (!validateStringInput(pwdManagerPassword1.getText())) {
            formDatafilled = false;
            JOptionPane.showMessageDialog(this, "Please enter password");
        }

        if(formDatafilled){
            //save data
               String userName = txtManagerUsername1.getText();
        String password = pwdManagerPassword1.getText();
        String serviceType = cmbServices.getSelectedItem().toString();
        String managerame = txtManagerName.getText();

        if (!business.getUserAccountDirectory().checkIfUsernameIsUnique(userName)) {
            JOptionPane.showMessageDialog(null, "UserName already taken!");
            txtManagerUsername1.setText("");
            pwdManagerPassword1.setText("");
        } else {

            if (serviceType.equals("CLEANING")) {
                CleaningServices cleaningService = cleaningServices.addCleaningService();
                cleaningService.setManagerName(managerame);
                cleaningService.setUserName(userName);
                cleaningService.setManagerType("CLEANING");
                business.setCleaningServices(cleaningServices);
                CleaningServicesRole role = new CleaningServicesRole();
                business.getUserAccountDirectory().createUserAccount(userName, managerame, password, role);
            } else if (serviceType.equals("EMERGENCY")) {
                EmergencyServices emergencyService = emergencyServices.addEmergencyService();
                emergencyService.setManagerName(managerame);
                emergencyService.setUserName(userName);
                emergencyService.setManagerType("EMERGENCY");
                business.setEmergencyServices(emergencyServices);
                EmergencyServicesRole role = new EmergencyServicesRole();
                business.getUserAccountDirectory().createUserAccount(userName, managerame, password, role);
            } else if (serviceType.equals("TECHNICAL")) {
                TechnicalServices technicalService = technicalServices.addGroundService();
                technicalService.setManagerName(managerame);
                technicalService.setUserName(userName);
                technicalService.setManagerType("TECHNICAL");
                business.setTechnicalServices(technicalServices);
                TechnicalServicesRole role = new TechnicalServicesRole();
                business.getUserAccountDirectory().createUserAccount(userName, managerame, password, role);
            } else if (serviceType.equals("SECURITY")) {
                SecurityServices securityService = securityServices.addSecurityService();
                securityService.setManagerName(managerame);
                securityService.setUserName(userName);
                securityService.setManagerType("SECURITY");
                business.setSecurityServices(securityServices);
                SecurityServicesRole role = new SecurityServicesRole();
                business.getUserAccountDirectory().createUserAccount(userName, managerame, password, role);
            }

            txtManagerName.setText("");
            cmbServices.setSelectedItem("SELECT SERVICE");
            txtManagerUsername1.setText("");
            pwdManagerPassword1.setText("");

            populateTable();
        }
        }
      
    }//GEN-LAST:event_btnCreateUser2ActionPerformed

    private static boolean validateStringInput(String userInput) {
        if (userInput.trim().equals("") || userInput == null) {
            return false;
        } else {
            return true;
        }
    }

    private static boolean validateIntegerInput(String userInput) {
        if (userInput.matches("^[0-9]*$") && userInput.length() == 10) {
            return true;
        } else {
            return false;
        }
    }
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblHumanResourceManagers.getModel();
        model.setRowCount(0);

        for (UserAccount userAccount : business.getUserAccountDirectory().getUserAccountList()) {
            Object[] row = new Object[4];
            CleaningServices cleaningService = null;
            EmergencyServices emergencyService = null;
            TechnicalServices groundService = null;
            SecurityServices securityService = null;
            if (cleaningServices != null && cleaningServices.getCleaningServices() != null && !cleaningServices.getCleaningServices().isEmpty()) {
                cleaningService = cleaningServices.getCleaningServices().stream().filter(x -> x.getManagerName().equals(userAccount.getName())).findAny().orElse(null);
            }
            if (emergencyServices != null && emergencyServices.getEmergencyServices() != null && !emergencyServices.getEmergencyServices().isEmpty()) {
                emergencyService = emergencyServices.getEmergencyServices().stream().filter(x -> x.getManagerName().equals(userAccount.getName())).findAny().orElse(null);
            }

            if (technicalServices != null && technicalServices.getGroundServices() != null && !technicalServices.getGroundServices().isEmpty()) {
                groundService = technicalServices.getGroundServices().stream().filter(x -> x.getManagerName().equals(userAccount.getName())).findAny().orElse(null);
            }

            if (securityServices != null && securityServices.getSecurityServices() != null && !securityServices.getSecurityServices().isEmpty()) {
                securityService = securityServices.getSecurityServices().stream().filter(x -> x.getManagerName().equals(userAccount.getName())).findAny().orElse(null);
            }
            if (userAccount.getRole() != null && userAccount.getRole().type != null && (userAccount.getRole().type == Role.RoleType.HumanResourceEntAdmin || userAccount.getRole().type == Role.RoleType.CleaningServicesRole)) {

                row[0] = userAccount;
                row[1] = userAccount.getPassword();
                row[2] = userAccount.getName();

                if (cleaningService != null) {
                    row[3] = cleaningService.getManagerType();
                } else if (emergencyService != null) {
                    row[3] = emergencyService.getManagerType();
                } else if (groundService != null) {
                    row[3] = groundService.getManagerType();
                } else if (securityService != null) {
                    row[3] = securityService.getManagerType();
                }
                model.addRow(row);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NavigationJPanel;
    private javax.swing.JButton btnCreateUser2;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JButton btnUpdateUser;
    private javax.swing.JComboBox<String> cmbServices;
    private javax.swing.JComboBox<String> cmbServices2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblAddUser2;
    private javax.swing.JLabel lblAddUser3;
    private javax.swing.JLabel lblManagerName2;
    private javax.swing.JLabel lblManagerName3;
    private javax.swing.JLabel lblPassword2;
    private javax.swing.JLabel lblPassword3;
    private javax.swing.JLabel lblRestaurantName1;
    private javax.swing.JLabel lblRestaurantName4;
    private javax.swing.JLabel lblRestaurantName5;
    private javax.swing.JLabel lblUserName2;
    private javax.swing.JLabel lblUserName3;
    private javax.swing.JPasswordField pwdManagerPassword1;
    private javax.swing.JPasswordField pwdManagerPassword2;
    private javax.swing.JTable tblHumanResourceManagers;
    private javax.swing.JTextField txtManagerName;
    private javax.swing.JTextField txtManagerName2;
    private javax.swing.JTextField txtManagerUsername1;
    private javax.swing.JTextField txtManagerUsername2;
    private javax.swing.JPanel workAreaPanel;
    // End of variables declaration//GEN-END:variables
}
