package ui.Enterprises;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import business.Business;
import business.Enterprise;
import business.Enterprises.EnterpriseDirectory;

import business.useraccount.UserAccount;
import business.merchandise.merchandiseShop;
import business.merchandise.merchandiseShopDirectory;
import business.role.ParkingManagerRole;
import business.role.PickandDropManagerRole;
import business.role.Role;
import business.ticketing.ParkingDirectory;
import business.ticketing.ParkingManager;
import business.ticketing.PickandDropDirectory;
import business.ticketing.PickandDropManager;
import java.awt.CardLayout;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aravindpolepeddi
 */
public class TicketingEntJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageRestaurantJPanel
     */
    private Business system;
    merchandiseShopDirectory merchShopDir;
    private ParkingDirectory parkingDirectory;
    private PickandDropDirectory pdDirectory;

    private JPanel userProcessContainer;
    private Boolean update = false;
    merchandiseShop merchShop = new merchandiseShop();

    Map<String, Enterprise> network;
    EnterpriseDirectory enterpriseDirectory;
    Enterprise enterprise;
    String networkString;

    public TicketingEntJPanel(JPanel userProcessContainer, UserAccount uadir, Business system) {
        initComponents();

        if (system.getNetworkList() == null) {
            this.network = new HashMap<String, Enterprise>();
        } else {
            this.network = system.getNetworkList();
        }

        if (system.getPdDirectory() == null) {
            pdDirectory = new PickandDropDirectory();
        } else {
            this.pdDirectory = system.getPdDirectory();
        }
        if (system.getParkingDirectory() == null) {
            parkingDirectory = new ParkingDirectory();
        } else {
            this.parkingDirectory = system.getParkingDirectory();
        }

        this.userProcessContainer = userProcessContainer;
        this.system = system;
        populateTable();
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) jTableTicketingManagers.getModel();
        model.setRowCount(0);
        for (UserAccount userAccount : system.getUserAccountDirectory().getUserAccountList()) {
            Object[] row = new Object[4];
            ParkingManager pm = null;
            PickandDropManager pdm = null;
            if (parkingDirectory != null && parkingDirectory.getParkingManagerList() != null && !parkingDirectory.getParkingManagerList().isEmpty()) {
                pm = parkingDirectory.getParkingManagerList().stream().filter(x -> x.getParkingManagerName().equals(userAccount.getName())).findAny().orElse(null);
            }
            if (pdDirectory != null && pdDirectory.getPdList() != null && !pdDirectory.getPdList().isEmpty()) {
                pdm = pdDirectory.getPdList().stream().filter(x -> x.getManagerName().equals(userAccount.getName())).findAny().orElse(null);
            }
            if (userAccount.getRole() != null && userAccount.getRole().type != null && userAccount.getRole().type == Role.RoleType.TicketingAdmin) {
                row[0] = userAccount.getUsername();
                row[1] = userAccount.getPassword();
                row[2] = userAccount.getName();
                if (pm != null) {
                    row[3] = pm.type.ParkingManager.toString();
                } else if (pdm != null) {
                    row[3] = pdm.type.PickandDropManager.toString();
                }
                model.addRow(row);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTicketingManagers = new javax.swing.JTable();
        jTextName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButtonSave = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtNetwork = new javax.swing.JTextField();
        lblRestaurantName1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(240, 255, 255));

        jTableTicketingManagers.setBackground(new java.awt.Color(255, 255, 255));
        jTableTicketingManagers.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTableTicketingManagers.setForeground(new java.awt.Color(0, 51, 51));
        jTableTicketingManagers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Username", "Password", "Name", "Organization"
            }
        ));
        jTableTicketingManagers.setOpaque(false);
        jTableTicketingManagers.setSelectionBackground(new java.awt.Color(0, 204, 204));
        jTableTicketingManagers.setSelectionForeground(new java.awt.Color(0, 51, 51));
        jScrollPane1.setViewportView(jTableTicketingManagers);

        jTextName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNameActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Enter  Name");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Enter Username");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Enter Password");

        jButtonSave.setBackground(new java.awt.Color(204, 255, 204));
        jButtonSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonSave.setForeground(new java.awt.Color(0, 153, 0));
        jButtonSave.setText("Save");
        jButtonSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("Organization");

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 0));
        jButton1.setText("Back");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Delete");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 0));
        jButton3.setText("Update");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Parking", "PickupandDrop", "SeatBooking" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("Network");

        lblRestaurantName1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRestaurantName1.setForeground(new java.awt.Color(0, 153, 153));
        lblRestaurantName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRestaurantName1.setText("Ticketing Enterprise");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tickets.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)
                                .addGap(351, 351, 351))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(102, 102, 102)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(47, 47, 47)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addGap(3, 3, 3)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSave))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblRestaurantName1, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jComboBox1, jPasswordField1, jTextName, jTextUsername, txtNetwork});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblRestaurantName1)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSave))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(221, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:

        StringBuilder Error = new StringBuilder();
        if (jComboBox1.getSelectedIndex() == 0) {
            ParkingManagerRole role = new ParkingManagerRole();
            system.getUserAccountDirectory().createUserAccount(jTextUsername.getText(), jTextName.getText(), jPasswordField1.getText(), role, txtNetwork.getText());

            if (network.containsKey(txtNetwork.getText())) {
                for (Map.Entry<String, Enterprise> iteration : network.entrySet()) {
                    if (iteration.getKey().equals(txtNetwork.getText())) {
                        if (iteration.getValue().getParkingDirectory() == null) {
                            parkingDirectory = new ParkingDirectory();
                            Enterprise enterprise = iteration.getValue();
                            ParkingManager parking = parkingDirectory.addParkingManager();
                            if (jTextName.getText().isEmpty()) {
                                Error.append("Enter Valid Name \n");
                            } else {
                                parking.setParkingManagerName(jTextName.getText());

                                jTextName.setText("");
                            }
                            if (jTextUsername.getText().isEmpty()) {
                                Error.append("Enter Capacity \n");
                            } else {
                                parking.setUsername(jTextUsername.getText());
                                jTextUsername.setText("");
                            }
                            if (jPasswordField1.getText().isEmpty()) {
                                Error.append("Enter Valid Start Date \n");
                            } else {
                                parking.setPassword(jPasswordField1.getText());
                                jPasswordField1.setText("");
                            }

//                            if (update == true) {
//                                update = false;
//                            } else {
//                                JOptionPane.showMessageDialog(this, Error);
//                            }
                            enterprise.setParkingDirectory(parkingDirectory);
                            network.put(txtNetwork.getText(), enterprise);
                            system.setNetworkList(network);
                        } else {
                            parkingDirectory = iteration.getValue().getParkingDirectory();
                            ParkingManager parking = parkingDirectory.addParkingManager();
                            if (jTextName.getText().isEmpty()) {
                                Error.append("Enter Valid Name \n");
                            } else {
                                parking.setParkingManagerName(jTextName.getText());

                                jTextName.setText("");
                            }
                            if (jTextUsername.getText().isEmpty()) {
                                Error.append("Enter Capacity \n");
                            } else {
                                parking.setUsername(jTextUsername.getText());
                                jTextUsername.setText("");
                            }
                            if (jPasswordField1.getText().isEmpty()) {
                                Error.append("Enter Valid Start Date \n");
                            } else {
                                parking.setPassword(jPasswordField1.getText());
                                jPasswordField1.setText("");
                            }

//                            if (update == true) {
//                                update = false;
//                            } else {
//                                JOptionPane.showMessageDialog(this, Error);
//                            }
                        }
                    }
                }
            } else {
                Enterprise enterprise = new Enterprise();
                ParkingDirectory parkingDirectory = new ParkingDirectory();
                ParkingManager parking = parkingDirectory.addParkingManager();
                if (jTextName.getText().isEmpty()) {
                    Error.append("Enter Valid Name \n");
                } else {
                    parking.setParkingManagerName(jTextName.getText());

                    jTextName.setText("");
                }
                if (jTextUsername.getText().isEmpty()) {
                    Error.append("Enter Capacity \n");
                } else {
                    parking.setUsername(jTextUsername.getText());
                    jTextUsername.setText("");
                }
                if (jPasswordField1.getText().isEmpty()) {
                    Error.append("Enter Valid Start Date \n");
                } else {
                    parking.setPassword(jPasswordField1.getText());
                    jPasswordField1.setText("");
                }

                if (update == true) {
                    update = false;
                }

                if (Error.isEmpty()) {
                    enterprise.setParkingDirectory(parkingDirectory);
                    network.put(txtNetwork.getText(), enterprise);
                    system.setNetworkList(network);
                } else {
                    JOptionPane.showMessageDialog(this, Error);
                }

            }
        }

        if (jComboBox1.getSelectedIndex() == 1) {
            PickandDropManagerRole role = new PickandDropManagerRole();
            system.getUserAccountDirectory().createUserAccount(jTextUsername.getText(), jTextName.getText(), jPasswordField1.getText(), role, txtNetwork.getText());

            if (network.containsKey(txtNetwork.getText())) {
                for (Map.Entry<String, Enterprise> iteration : network.entrySet()) {
                    if (iteration.getKey().equals(txtNetwork.getText())) {
                        if (iteration.getValue().getPdDirectory() == null) {
                            pdDirectory = new PickandDropDirectory();
                            Enterprise enterprise = iteration.getValue();
                            PickandDropManager pd = pdDirectory.addPickDropManager();
                            if (jTextName.getText().isEmpty()) {
                                Error.append("Enter Valid Name \n");
                            } else {
                                pd.setManagerName(jTextName.getText());
                                jTextName.setText("");
                            }
                            if (jTextUsername.getText().isEmpty()) {
                                Error.append("Enter Capacity \n");
                            } else {
                                pd.setUsername(jTextUsername.getText());
                                jTextUsername.setText("");
                            }
                            if (jPasswordField1.getText().isEmpty()) {
                                Error.append("Enter Valid Start Date \n");
                            } else {
                                pd.setPassword(jPasswordField1.getText());
                                jPasswordField1.setText("");
                            }

//                            if (update == true) {
//                                update = false;
//                            } else {
//                                JOptionPane.showMessageDialog(this, Error);
//                            }
                            enterprise.setPdDirectory(pdDirectory);
                            network.put(txtNetwork.getText(), enterprise);
                            system.setNetworkList(network);
                        } else {
                            pdDirectory = iteration.getValue().getPdDirectory();
                            PickandDropManager pd = pdDirectory.addPickDropManager();
                            if (jTextName.getText().isEmpty()) {
                                Error.append("Enter Valid Name \n");
                            } else {
                                pd.setManagerName(jTextName.getText());
                                jTextName.setText("");
                            }
                            if (jTextUsername.getText().isEmpty()) {
                                Error.append("Enter Capacity \n");
                            } else {
                                pd.setUsername(jTextUsername.getText());
                                jTextUsername.setText("");
                            }
                            if (jPasswordField1.getText().isEmpty()) {
                                Error.append("Enter Valid Start Date \n");
                            } else {
                                pd.setPassword(jPasswordField1.getText());
                                jPasswordField1.setText("");
                            }

//                            if (update == true) {
//                                update = false;
//                            } else {
//                                JOptionPane.showMessageDialog(this, Error);
//                            }
                        }
                    }
                }
            } else {
                Enterprise enterprise = new Enterprise();
                PickandDropDirectory pdDir = new PickandDropDirectory();
                PickandDropManager pd = pdDir.addPickDropManager();
                if (jTextName.getText().isEmpty()) {
                    Error.append("Enter Valid Name \n");
                } else {
                    pd.setManagerName(jTextName.getText());
                    jTextName.setText("");
                }
                if (jTextUsername.getText().isEmpty()) {
                    Error.append("Enter Capacity \n");
                } else {
                    pd.setUsername(jTextUsername.getText());
                    jTextUsername.setText("");
                }
                if (jPasswordField1.getText().isEmpty()) {
                    Error.append("Enter Valid Start Date \n");
                } else {
                    pd.setPassword(jPasswordField1.getText());
                    jPasswordField1.setText("");
                }

                if (update == true) {
                    update = false;
                }

                if (Error.isEmpty()) {
                    enterprise.setParkingDirectory(parkingDirectory);
                    network.put(txtNetwork.getText(), enterprise);
                    system.setNetworkList(network);
                } else {
                    JOptionPane.showMessageDialog(this, Error);
                }

            }
        }
        populateTable();

    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jTextNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (!update) {
            userProcessContainer.remove(this);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.previous(userProcessContainer);
        } else {
            JOptionPane.showMessageDialog(this, "Please Save your updated Role");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int index = jTableTicketingManagers.getSelectedRow();
        if (index < 0) {
            JOptionPane.showMessageDialog(this, "Please select an Manager");
            return;
        } else {
            DefaultTableModel model = (DefaultTableModel) jTableTicketingManagers.getModel();
            UserAccount selectedUserAccount = (UserAccount) model.getValueAt(index, 0);
            UserAccount deleteUserAccount = system.getUserAccountDirectory().fetchUserAccountUsingUserName(selectedUserAccount.getUsername());
            system.getUserAccountDirectory().getUserAccountList().remove(deleteUserAccount);

            PickandDropManager pd = system.getPdDirectory().findPickandDrop(deleteUserAccount.getUsername());
            if (pd != null) {
                system.getPdDirectory().getPdList().remove(pd);
            }

            ParkingManager parking = system.getParkingDirectory().findParking(deleteUserAccount.getUsername());
            if (parking != null) {
                system.getParkingDirectory().getParkingList().remove(parking);
            }
        }
        /*
        ParkingManager parking = system.getParkingDirectory().findParking(deleteUserAccount.getUsername());
        if (parking != null) {
        system.getParkingDirectory().getParkingList().remove(parking);
        }
        }
         */
        populateTable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int index = jTableTicketingManagers.getSelectedRow();
        if (index < 0) {
            JOptionPane.showMessageDialog(this, "Please select an Manager");
            return;
        } else {
            DefaultTableModel model = (DefaultTableModel) jTableTicketingManagers.getModel();
            UserAccount selectedUserAccount = (UserAccount) model.getValueAt(index, 0);
            UserAccount deleteUserAccount = system.getUserAccountDirectory().fetchUserAccountUsingUserName(selectedUserAccount.getUsername());
            system.getUserAccountDirectory().getUserAccountList().remove(deleteUserAccount);

            PickandDropManager pd = system.getPdDirectory().findPickandDrop(deleteUserAccount.getUsername());
            if (pd != null) {
                system.getPdDirectory().getPdList().remove(pd);
            }

            ParkingManager parking = system.getParkingDirectory().findParking(deleteUserAccount.getUsername());
            if (parking != null) {
                system.getParkingDirectory().getParkingList().remove(parking);
            }
            update = true;
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTicketingManagers;
    private javax.swing.JTextField jTextName;
    private javax.swing.JTextField jTextUsername;
    private javax.swing.JLabel lblRestaurantName1;
    private javax.swing.JTextField txtNetwork;
    // End of variables declaration//GEN-END:variables
}
