/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Organization.HR;

import business.Business;
import business.Enterprise;
import business.Enterprises.EnterpriseDirectory;
import business.FlagClass;
import business.hrservices.CleaningServices;
import business.hrservices.CleaningServicesDirectory;
import business.hrservices.Staff;
import business.hrservices.StaffDirectory;
import business.useraccount.UserAccount;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author deepv
 */
public class CleaningServicesJPanel extends javax.swing.JPanel {

    StaffDirectory staffDirectory;
    CleaningServicesDirectory cleaningDirectory;
    CleaningServices cleaningServices;
    String managerName;
    FlagClass flags;
    Map<String, Enterprise> network;
    EnterpriseDirectory enterpriseDirectory;
    Enterprise enterprise;
    String networkString;

    /**
     * Creates new form CleaningServicesJPanel
     */
    public CleaningServicesJPanel(JPanel userProcessContainer, UserAccount account, Business business) {
        initComponents();
        txtInstructions.setVisible(false);
        this.networkString = account.getNetwork();

        if (business.getNetworkList() == null) {
            this.network = new HashMap<String, Enterprise>();
        } else {
            this.network = business.getNetworkList();
        }

        this.enterprise = business.findEnterpriseByNetwork(account.getNetwork());

        this.managerName = account.getName();
        this.flags = new FlagClass();

        if (enterprise.getCleaningServices() == null) {
            this.cleaningDirectory = new CleaningServicesDirectory();
        } else {
            this.cleaningDirectory = enterprise.getCleaningServices();
        }

        this.cleaningServices = cleaningDirectory.findCleaningServiceByManagerName(managerName);

        if (cleaningServices.getStaffDirectory() == null) {
            this.staffDirectory = new StaffDirectory();
        } else {
            this.staffDirectory = cleaningServices.getStaffDirectory();
        }

        populateStaff();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        NavigationJPanel = new javax.swing.JPanel();
        btnMenu = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        workAreaPanel = new javax.swing.JPanel();
        lblRestaurantName = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblStaff = new javax.swing.JTable();
        pnlFeedbackTable = new javax.swing.JPanel();
        btnDetails = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        txtInstructions = new javax.swing.JTextField();
        AddNewStaffMember = new javax.swing.JPanel();
        lblRestaurantName1 = new javax.swing.JLabel();
        btnBack3 = new javax.swing.JButton();
        lblFullName = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnBack4 = new javax.swing.JButton();
        lblProfileImage = new javax.swing.JLabel();
        btnProfileImage = new javax.swing.JButton();
        lblImageSlot = new javax.swing.JLabel();
        ViewDetailsPanel = new javax.swing.JPanel();
        lblStaffMemberName = new javax.swing.JLabel();
        btnBack5 = new javax.swing.JButton();
        lblFullName1 = new javax.swing.JLabel();
        txtFullName1 = new javax.swing.JTextField();
        lblPhoneNumber1 = new javax.swing.JLabel();
        txtPhoneNumber1 = new javax.swing.JTextField();
        lblEmail1 = new javax.swing.JLabel();
        txtEmail1 = new javax.swing.JTextField();
        lblProfileImageView = new javax.swing.JLabel();

        NavigationJPanel.setBackground(new java.awt.Color(0, 51, 51));

        btnMenu.setBackground(new java.awt.Color(206, 217, 217));
        btnMenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(0, 51, 51));
        btnMenu.setText("ADD STAFF");
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuMouseExited(evt);
            }
        });
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NavigationJPanelLayout = new javax.swing.GroupLayout(NavigationJPanel);
        NavigationJPanel.setLayout(NavigationJPanelLayout);
        NavigationJPanelLayout.setHorizontalGroup(
            NavigationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavigationJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        NavigationJPanelLayout.setVerticalGroup(
            NavigationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavigationJPanelLayout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(391, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(NavigationJPanel);

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        workAreaPanel.setBackground(new java.awt.Color(240, 255, 255));

        lblRestaurantName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRestaurantName.setForeground(new java.awt.Color(0, 153, 153));
        lblRestaurantName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRestaurantName.setText("CLEANING SERVICES");

        tblStaff.setBackground(new java.awt.Color(255, 255, 255));
        tblStaff.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STAFF MEMBER", "ASSIGNED TO", "STATUS"
            }
        ));
        tblStaff.setSelectionBackground(new java.awt.Color(153, 209, 232));
        tblStaff.setSelectionForeground(new java.awt.Color(0, 51, 51));
        jScrollPane3.setViewportView(tblStaff);

        pnlFeedbackTable.setBackground(new java.awt.Color(240, 255, 255));

        javax.swing.GroupLayout pnlFeedbackTableLayout = new javax.swing.GroupLayout(pnlFeedbackTable);
        pnlFeedbackTable.setLayout(pnlFeedbackTableLayout);
        pnlFeedbackTableLayout.setHorizontalGroup(
            pnlFeedbackTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );
        pnlFeedbackTableLayout.setVerticalGroup(
            pnlFeedbackTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 103, Short.MAX_VALUE)
        );

        btnDetails.setBackground(new java.awt.Color(255, 255, 255));
        btnDetails.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDetails.setForeground(new java.awt.Color(0, 153, 51));
        btnDetails.setText("DETAILS");
        btnDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDetailsMouseExited(evt);
            }
        });
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });

        btnSubmit.setBackground(new java.awt.Color(204, 255, 204));
        btnSubmit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(0, 102, 0));
        btnSubmit.setText("VIEW INSTRUCTIONS");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        txtInstructions.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtInstructions.setForeground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout workAreaPanelLayout = new javax.swing.GroupLayout(workAreaPanel);
        workAreaPanel.setLayout(workAreaPanelLayout);
        workAreaPanelLayout.setHorizontalGroup(
            workAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAreaPanelLayout.createSequentialGroup()
                .addGroup(workAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(workAreaPanelLayout.createSequentialGroup()
                        .addGap(664, 664, 664)
                        .addComponent(pnlFeedbackTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(workAreaPanelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(workAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(workAreaPanelLayout.createSequentialGroup()
                                .addComponent(btnDetails)
                                .addGap(18, 18, 18)
                                .addComponent(btnSubmit))
                            .addComponent(txtInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(workAreaPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblRestaurantName, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        workAreaPanelLayout.setVerticalGroup(
            workAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAreaPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblRestaurantName)
                .addGap(50, 50, 50)
                .addGroup(workAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDetails)
                    .addComponent(btnSubmit))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(pnlFeedbackTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        jLayeredPane1.add(workAreaPanel, "card2");

        AddNewStaffMember.setBackground(new java.awt.Color(240, 255, 255));

        lblRestaurantName1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRestaurantName1.setForeground(new java.awt.Color(0, 153, 153));
        lblRestaurantName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRestaurantName1.setText("ADD NEW CLEANING STAFF");

        btnBack3.setBackground(new java.awt.Color(255, 204, 204));
        btnBack3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack3.setForeground(new java.awt.Color(255, 0, 51));
        btnBack3.setText("BACK");
        btnBack3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBack3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBack3MouseExited(evt);
            }
        });
        btnBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack3ActionPerformed(evt);
            }
        });

        lblFullName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblFullName.setText("FULL NAME :");

        lblPhoneNumber.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPhoneNumber.setText("PHONE NUMBER : ");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblEmail.setText("EMAIL : ");

        btnBack4.setBackground(new java.awt.Color(215, 254, 211));
        btnBack4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack4.setForeground(new java.awt.Color(72, 151, 64));
        btnBack4.setText("SAVE");
        btnBack4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBack4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBack4MouseExited(evt);
            }
        });
        btnBack4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack4ActionPerformed(evt);
            }
        });

        lblProfileImage.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblProfileImage.setText("Profile Image : ");

        btnProfileImage.setText("Browse Image");
        btnProfileImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddNewStaffMemberLayout = new javax.swing.GroupLayout(AddNewStaffMember);
        AddNewStaffMember.setLayout(AddNewStaffMemberLayout);
        AddNewStaffMemberLayout.setHorizontalGroup(
            AddNewStaffMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddNewStaffMemberLayout.createSequentialGroup()
                .addGroup(AddNewStaffMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddNewStaffMemberLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblRestaurantName1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddNewStaffMemberLayout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(lblImageSlot, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddNewStaffMemberLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(AddNewStaffMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBack4, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AddNewStaffMemberLayout.createSequentialGroup()
                                .addGroup(AddNewStaffMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFullName, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPhoneNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblProfileImage, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(AddNewStaffMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnProfileImage))))))
                .addGap(94, 499, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddNewStaffMemberLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBack3)
                .addGap(150, 150, 150))
        );
        AddNewStaffMemberLayout.setVerticalGroup(
            AddNewStaffMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddNewStaffMemberLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnBack3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRestaurantName1)
                .addGap(34, 34, 34)
                .addComponent(lblImageSlot, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(AddNewStaffMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFullName)
                    .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(AddNewStaffMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPhoneNumber)
                    .addGroup(AddNewStaffMemberLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddNewStaffMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddNewStaffMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfileImage)
                    .addComponent(btnProfileImage))
                .addGap(72, 72, 72)
                .addComponent(btnBack4)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        jLayeredPane1.add(AddNewStaffMember, "card3");

        ViewDetailsPanel.setBackground(new java.awt.Color(240, 255, 255));

        lblStaffMemberName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblStaffMemberName.setForeground(new java.awt.Color(0, 153, 153));
        lblStaffMemberName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStaffMemberName.setText("<<Staff member name>>");

        btnBack5.setBackground(new java.awt.Color(255, 204, 204));
        btnBack5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack5.setForeground(new java.awt.Color(255, 0, 51));
        btnBack5.setText("BACK");
        btnBack5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBack5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBack5MouseExited(evt);
            }
        });
        btnBack5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack5ActionPerformed(evt);
            }
        });

        lblFullName1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblFullName1.setText("FULL NAME :");

        txtFullName1.setEditable(false);

        lblPhoneNumber1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPhoneNumber1.setText("PHONE NUMBER : ");

        txtPhoneNumber1.setEditable(false);

        lblEmail1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblEmail1.setText("EMAIL : ");

        txtEmail1.setEditable(false);

        javax.swing.GroupLayout ViewDetailsPanelLayout = new javax.swing.GroupLayout(ViewDetailsPanel);
        ViewDetailsPanel.setLayout(ViewDetailsPanelLayout);
        ViewDetailsPanelLayout.setHorizontalGroup(
            ViewDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewDetailsPanelLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(ViewDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFullName1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPhoneNumber1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEmail1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(ViewDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProfileImageView, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFullName1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhoneNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(608, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewDetailsPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBack5)
                .addGap(53, 53, 53))
            .addComponent(lblStaffMemberName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ViewDetailsPanelLayout.setVerticalGroup(
            ViewDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewDetailsPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnBack5)
                .addGap(39, 39, 39)
                .addComponent(lblStaffMemberName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProfileImageView, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(ViewDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFullName1)
                    .addComponent(txtFullName1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(ViewDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPhoneNumber1)
                    .addGroup(ViewDetailsPanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txtPhoneNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addGroup(ViewDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmail1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(164, Short.MAX_VALUE))
        );

        jLayeredPane1.add(ViewDetailsPanel, "card4");

        jSplitPane1.setRightComponent(jLayeredPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseEntered

    }//GEN-LAST:event_btnMenuMouseEntered

    private void btnMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseExited

    }//GEN-LAST:event_btnMenuMouseExited

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        switchPanels(AddNewStaffMember);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnDetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetailsMouseEntered

    }//GEN-LAST:event_btnDetailsMouseEntered

    private void btnDetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetailsMouseExited

    }//GEN-LAST:event_btnDetailsMouseExited

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
        int selectedRowIndex = tblStaff.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a Staff member");
            return;
        } else {
            switchPanels(ViewDetailsPanel);
            DefaultTableModel model = (DefaultTableModel) tblStaff.getModel();
            Staff selectedStaff = (Staff) model.getValueAt(selectedRowIndex, 0);
            lblStaffMemberName.setText(selectedStaff.getFullName());
            txtFullName1.setText(selectedStaff.getFullName());
            txtPhoneNumber1.setText(selectedStaff.getPhoneNumber());
            txtEmail1.setText(selectedStaff.getEmail());

            ImageIcon image = new ImageIcon(selectedStaff.getProfileImagePath());
            Image resizedImage = image.getImage().getScaledInstance(149, 151, Image.SCALE_SMOOTH);
            lblProfileImageView.setIcon(new ImageIcon(resizedImage));
        }
    }//GEN-LAST:event_btnDetailsActionPerformed

    private void btnBack3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBack3MouseEntered

    }//GEN-LAST:event_btnBack3MouseEntered

    private void btnBack3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBack3MouseExited

    }//GEN-LAST:event_btnBack3MouseExited

    private void btnBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack3ActionPerformed
        switchPanels(workAreaPanel);
    }//GEN-LAST:event_btnBack3ActionPerformed

    private void btnBack4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBack4MouseEntered

    }//GEN-LAST:event_btnBack4MouseEntered

    private void btnBack4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBack4MouseExited

    }//GEN-LAST:event_btnBack4MouseExited

    private void btnBack4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack4ActionPerformed
        Staff staffMember = staffDirectory.addStaffMembers();
        staffMember.setFullName(txtFullName.getText());
        staffMember.setPhoneNumber(txtPhoneNumber.getText());
        staffMember.setEmail(txtEmail.getText());
        staffMember.setStaffType("CLEANING");
        staffMember.setManager(managerName);
        staffMember.setProfileImagePath(flags.getImageFilePath());
        cleaningServices.setStaffDirectory(staffDirectory);
        JOptionPane.showMessageDialog(null, "Staff member added successfully.");
        switchPanels(workAreaPanel);
        populateStaff();
        txtFullName.setText("");
        txtPhoneNumber.setText("");
        txtEmail.setText("");
        lblImageSlot.setText("");
    }//GEN-LAST:event_btnBack4ActionPerformed

    private void btnProfileImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileImageActionPerformed
        JFileChooser browseimage = new JFileChooser();
        FileNameExtensionFilter fileExtension = new FileNameExtensionFilter(".JPG and .PNG", "jpg", "png");
        browseimage.setFileFilter(fileExtension);
        int showDialogue = browseimage.showOpenDialog(null);

        if (showDialogue == JFileChooser.APPROVE_OPTION) {
            File file = browseimage.getSelectedFile();
            String selectedImagePath = file.getAbsolutePath();
            JOptionPane.showConfirmDialog(this, "Set this image as the staff profile image?");
            flags.setImageFilePath(selectedImagePath);

            ImageIcon image = new ImageIcon(flags.getImageFilePath());
            Image resizedImage = image.getImage().getScaledInstance(149, 151, Image.SCALE_SMOOTH);
            lblImageSlot.setIcon(new ImageIcon(resizedImage));
        }
    }//GEN-LAST:event_btnProfileImageActionPerformed

    private void btnBack5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBack5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBack5MouseEntered

    private void btnBack5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBack5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBack5MouseExited

    private void btnBack5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack5ActionPerformed
        switchPanels(workAreaPanel);
    }//GEN-LAST:event_btnBack5ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        int selectedRowIndex = tblStaff.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a Staff member");
            return;
        } else {
            DefaultTableModel model = (DefaultTableModel) tblStaff.getModel();
            Staff selectedStaff = (Staff) model.getValueAt(selectedRowIndex, 0);
            txtInstructions.setText(selectedStaff.getInstructions());
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void switchPanels(Component component) {
        jLayeredPane1.removeAll();
        jLayeredPane1.add(component);
        jLayeredPane1.revalidate();
        jLayeredPane1.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddNewStaffMember;
    private javax.swing.JPanel NavigationJPanel;
    private javax.swing.JPanel ViewDetailsPanel;
    private javax.swing.JButton btnBack3;
    private javax.swing.JButton btnBack4;
    private javax.swing.JButton btnBack5;
    private javax.swing.JButton btnDetails;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnProfileImage;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmail1;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblFullName1;
    private javax.swing.JLabel lblImageSlot;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblPhoneNumber1;
    private javax.swing.JLabel lblProfileImage;
    private javax.swing.JLabel lblProfileImageView;
    private javax.swing.JLabel lblRestaurantName;
    private javax.swing.JLabel lblRestaurantName1;
    private javax.swing.JLabel lblStaffMemberName;
    private javax.swing.JPanel pnlFeedbackTable;
    private javax.swing.JTable tblStaff;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtFullName1;
    private javax.swing.JTextField txtInstructions;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtPhoneNumber1;
    private javax.swing.JPanel workAreaPanel;
    // End of variables declaration//GEN-END:variables

    private void populateStaff() {
        DefaultTableModel model = (DefaultTableModel) tblStaff.getModel();
        model.setRowCount(0);

        for (Staff staffMember : staffDirectory.getStaffList()) {
            Object[] row = new Object[3];
            if (staffMember.getStaffType().equals("CLEANING")) {

                row[0] = staffMember;
                row[1] = staffMember.getEmail();
                row[2] = staffMember.getStatus();
                model.addRow(row);
            }
        }
    }
}
